import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Key-health engine for the help-i18n skill. The page path is the key. Checks
// page-tree parity for every configured language (exit 1 on drift) and reports
// bold UI labels that do not match an English string in diamond-app. Writes
// .agents/skills/help-i18n/docs/_generated/STATE.md.
// Tone, terminology, and translation coverage are checked in diamond-translate.

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const navigationPath = path.join(root, 'config/navigation/index.json');
const stateFile = path.join(root, '.agents/skills/help-i18n/docs/_generated/STATE.md');
const defaultLanguage = 'en';

const labelSources = [
    { dirs: ['guides', 'academy', 'troubleshooting'], project: 'diamond-app' },
];

const navigation = JSON.parse(readFileSync(navigationPath, 'utf8'));
const trees = collectLanguageTrees(navigation);
const englishPages = trees.get(defaultLanguage) || [];

const parity = [
    ...checkPagesExist(trees),
    ...checkLanguageParity(trees, englishPages),
    ...checkStrayLanguageDirs(trees),
];
const labels = labelSources.map(checkBoldLabels);
const drift = parity.length;

const report = [
    '# i18n key-health report',
    '',
    '> Auto-generated by `npm run i18n:audit`. Do not edit. Regenerate after page or navigation changes.',
    '> Tone, terminology, and translation coverage are checked in diamond-translate.',
    `> Generated: ${new Date().toISOString()}`,
    '',
    '## Inventory',
    '',
    `- **Languages (navigation)**: ${[...trees.keys()].join(', ')}${navigation.languages ? '' : ' (no `languages` configured)'}`,
    `- **English pages**: ${englishPages.length}`,
    ...labels.map((l) => `- **Bold labels vs ${l.project}**: ${l.summary}`),
    '',
    renderSection('Page-tree parity', parity, 'No drift found.'),
    ...labels.map((l) => renderSection(`Bold labels without a ${l.project} English string (report only)`, l.findings, l.empty)),
    '---',
    '',
    `Drift findings: **${drift}**. Exit code ${drift ? 1 : 0}.`,
].join('\n');

mkdirSync(path.dirname(stateFile), { recursive: true });
writeFileSync(stateFile, `${report}\n`);
if (process.argv.includes('--json')) {
    const reportOnly = labels.flatMap((l) => l.findings);
    console.log(JSON.stringify({ keys: englishPages.length, drift: parity, reportOnly }, null, 2));
} else {
    console.log(`Wrote ${path.relative(root, stateFile)}`);
    console.log(`Drift findings: ${drift}`);
}
process.exitCode = drift ? 1 : 0;

function collectLanguageTrees(nav) {
    if (!Array.isArray(nav.languages)) return new Map([[defaultLanguage, collectPages(nav)]]);
    return new Map(nav.languages.map((entry) => [entry.language, collectPages(entry)]));
}

function collectPages(node) {
    const pages = [];
    const walk = (value) => {
        if (typeof value === 'string') {
            if (!pages.includes(value)) pages.push(value);
        } else if (Array.isArray(value)) {
            value.forEach(walk);
        } else if (value && typeof value === 'object') {
            if (typeof value.root === 'string') walk(value.root);
            for (const key of ['pages', 'groups', 'tabs', 'anchors', 'dropdowns', 'menu']) walk(value[key]);
        }
    };
    walk(node);
    return pages;
}

function checkPagesExist(languageTrees) {
    const out = [];
    for (const [language, pages] of languageTrees) {
        for (const page of pages) {
            if (!existsSync(path.join(root, `${page}.mdx`))) {
                out.push({ location: `${language}: ${page}`, detail: 'In navigation but no .mdx file' });
            }
        }
    }
    return out;
}

function checkLanguageParity(languageTrees, english) {
    const out = [];
    for (const [language, pages] of languageTrees) {
        if (language === defaultLanguage) continue;
        const expected = english.map((page) => `${language}/${page}`);
        for (const page of expected.filter((p) => !pages.includes(p))) {
            out.push({ location: `${language}: ${page}`, detail: 'English page has no mirror in this language' });
        }
        for (const page of pages.filter((p) => !expected.includes(p))) {
            out.push({ location: `${language}: ${page}`, detail: 'Page has no English source at the same path' });
        }
    }
    return out;
}

function checkStrayLanguageDirs(languageTrees) {
    return readdirSync(root)
        .filter((name) => /^[a-z]{2}(-[A-Za-z]{2,4})?$/.test(name) && statSync(path.join(root, name)).isDirectory())
        .filter((name) => !languageTrees.has(name))
        .map((name) => ({ location: `${name}/`, detail: 'Language folder on disk but not in navigation.languages' }));
}

function checkBoldLabels({ dirs, project }) {
    const localeDir = path.resolve(root, `../${project}/public/locales/en`);
    const present = dirs.filter((dir) => existsSync(path.join(root, dir)));
    if (!present.length) {
        return { project, summary: `no ${dirs.join(', ')} pages`, findings: [], empty: 'No pages to check.' };
    }
    if (!existsSync(localeDir)) {
        return { project, summary: 'skipped (not checked out)', findings: [], empty: `Skipped: ${project} is not checked out.` };
    }

    const strings = new Set();
    for (const file of walkFiles(localeDir, '.json')) collectStrings(JSON.parse(readFileSync(file, 'utf8')), strings);

    const unmatched = new Map();
    let total = 0;
    for (const dir of present) {
        for (const file of walkFiles(path.join(root, dir), '.mdx')) {
            const source = readFileSync(file, 'utf8');
            for (const match of source.matchAll(/\*\*([^*\n]+)\*\*/g)) {
                total += 1;
                const label = match[1].trim();
                if (strings.has(label.toLowerCase())) continue;
                const entry = unmatched.get(label) || { count: 0, first: path.relative(root, file) };
                entry.count += 1;
                unmatched.set(label, entry);
            }
        }
    }

    const findings = [...unmatched.entries()]
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([label, { count, first }]) => ({ location: label, detail: `${count}× (first in ${first})` }));
    const matched = total - [...unmatched.values()].reduce((sum, e) => sum + e.count, 0);
    return { project, summary: `${matched} of ${total} match`, findings, empty: 'None found.' };
}

function collectStrings(value, acc) {
    if (typeof value === 'string') acc.add(value.trim().toLowerCase());
    else if (value && typeof value === 'object') Object.values(value).forEach((child) => collectStrings(child, acc));
}

function walkFiles(dir, ext, acc = []) {
    for (const name of readdirSync(dir)) {
        const full = path.join(dir, name);
        if (statSync(full).isDirectory()) walkFiles(full, ext, acc);
        else if (name.endsWith(ext)) acc.push(full);
    }
    return acc;
}

function renderSection(title, findings, empty) {
    if (!findings.length) return `## ${title}\n\n${empty}\n`;
    return `## ${title}\n\n${findings.map((f) => `- **${f.location}** — ${f.detail}`).join('\n')}\n`;
}
